@startuml
'https://plantuml.com/class-diagram
class Computer {
    mouse:Mouse = new Mouse
    monitor:Monitor = new Monitor
}
class Mouse
class Monitor

Mouse --* Computer
Monitor --* Computer

@enduml